"""Command-line interface for the DNI OCR + Qwen pipeline."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable, Optional

from . import DEFAULT_OUTPUT_DIR, DEFAULT_QWEN_MODEL_PATH
from .logging_service import logging_service
from .workflow import (
    iter_image_paths,
    process_directory,
    process_image,
    save_json,
    cleanup_resources,
)

LOGGER = logging_service.get_logger("dni_pipeline.cli")


def build_parser() -> argparse.ArgumentParser:
    """Create the CLI argument parser."""
    parser = argparse.ArgumentParser(
        description="Extract structured data from Spanish DNI images.",
    )
    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument("--image", type=Path, help="Path to a single DNI image.")
    source_group.add_argument(
        "--input-dir",
        type=Path,
        help="Directory containing DNI images.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Directory to store per-image JSON results (default: {DEFAULT_OUTPUT_DIR}).",
    )
    parser.add_argument(
        "--ocr-max-side",
        type=int,
        default=1600,
        help="Maximum side length for the OCR variant.",
    )
    parser.add_argument(
        "--vlm-size",
        type=int,
        default=512,
        help="Target square size for the VLM input.",
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=256,
        help="Maximum tokens generated by the VLM.",
    )
    parser.add_argument(
        "--model-path",
        type=str,
        default=str(DEFAULT_QWEN_MODEL_PATH),
        help="Path to the Qwen3-VL-8B-Instruct model directory or a Hugging Face repo id.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable debug logging.",
    )
    parser.add_argument(
        "--cleanup",
        action="store_true",
        help="Unload models and free memory after processing.",
    )
    parser.add_argument(
        "--disable-card-crop",
        dest="enable_card_crop",
        action="store_false",
        help="Desactiva el recorte automático del DNI antes de pasarlo al VLM.",
    )
    parser.set_defaults(enable_card_crop=True)
    return parser


def main(argv: Optional[Iterable[str]] = None) -> int:
    """CLI entry point."""
    parser = build_parser()
    args = parser.parse_args(argv)

    logging_service.configure(args.verbose)

    image_paths = []
    if args.image:
        image_paths = [args.image]
    elif args.input_dir:
        try:
            image_paths = process_directory(args.input_dir)
        except NotADirectoryError as exc:
            LOGGER.error("%s", exc)
            return 1
        if not image_paths:
            LOGGER.error("No supported image files found in %s", args.input_dir)
            return 1

    output_dir: Path | None = args.output_dir
    if args.output_dir:
        output_dir.mkdir(parents=True, exist_ok=True)

    exit_code = 0
    for image_path in image_paths:
        record = process_image(
            image_path=image_path,
            ocr_max_side=args.ocr_max_side,
            vlm_size=args.vlm_size,
            max_new_tokens=args.max_new_tokens,
            model_path=args.model_path,
            enable_card_crop=args.enable_card_crop,
            processed_image_dir=output_dir,
        )
        print(json.dumps(record, ensure_ascii=False))
        if output_dir:
            output_name = image_path.with_suffix(".json").name
            save_json(record, output_dir / output_name)

    if args.cleanup:
        cleanup_resources()

    return exit_code


if __name__ == "__main__":
    sys.exit(main())
